### ISSUE TITLE
Table management plugin?

### ISSUE THREAD

**Issue by knuch** [epfl-idevelop/doc-epfl-antistatique#2]
Tables are not available by default in the wordpress WYSIWYG. Do you intend to use a certain plugin to allow this? @GregLeBarbar

**Comment by GregLeBarbar** [comment]
On utilise le WYSIWYG [tinymce advanced](https://fr.wordpress.org/plugins/tinymce-advanced/). Ce plugin permet l'utilisation des tableaux

**Comment by knuch** [comment]
thanks!
