### ISSUE TITLE
Source: News press release

### ISSUE THREAD

**Issue by knuch** [epfl-idevelop/doc-epfl-antistatique#3]
from which service does the press release news come from? @GregLeBarbar  
https://github.com/epfl-idevelop/elements/issues/53

**Comment by GregLeBarbar** [comment]
Les communiqués de presse proviennent également de l'outil actu.epfl.ch : 
Il existe un filtre pour les communiqués de presse : &projects=190
https://actu.epfl.ch/search/mediacom/?keywords=&date_filter=all&projects=190&search=Rechercher

**Comment by knuch** [comment]
Okay, thank!
